# Generated by Django 5.2.6 on 2025-10-06 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='contacto',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='anuncios/pdfs/'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='frase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='foto_portada',
            field=models.ImageField(blank=True, default='entidades/default.webp', null=True, upload_to='entidades/'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidad_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='usuarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'usuario'}, related_name='entidades_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/banners/'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
