# Generated by Django 5.2.6 on 2025-09-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_anuncio_archivo_pdf_anuncio_frase_entidad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entidades/'),
        ),
    ]
