# Generated by Django 5.2.6 on 2025-09-22 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_anuncio_banner_alter_entidad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='image',
        ),
        migrations.AddField(
            model_name='entidad',
            name='foto_portada',
            field=models.ImageField(blank=True, default='entidades/default.jpg', null=True, upload_to='entidades/'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidad_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='usuarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'usuario'}, related_name='entidades_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(blank=True, default='entidades/default.jpg', null=True, upload_to='banners/'),
        ),
    ]
