# Generated by Django 5.2.6 on 2025-10-09 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='gestionadores',
            field=models.ManyToManyField(related_name='entidades_gestionadas', through='accounts.GestionEntidad', to=settings.AUTH_USER_MODEL),
        ),
    ]
