# Generated by Django 5.2.6 on 2025-10-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_entidad_gestionadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='gestionadores',
        ),
    ]
