# Generated by Django 5.2.6 on 2025-09-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_entidad_image_entidad_foto_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(blank=True, default='entidades/default.webp', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='foto_portada',
            field=models.ImageField(blank=True, default='entidades/default.webp', null=True, upload_to='entidades/'),
        ),
    ]
