# Generated by Django 5.2.6 on 2025-10-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_entidad_gestionadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
