# Generated by Django 5.2.6 on 2025-09-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_anuncio_banner_alter_entidad_foto_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='contacto',
        ),
    ]
