# Generated by Django 5.2.6 on 2025-09-23 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_entidad_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='anuncios/pdfs/'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/banners/'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
