# Generated by Django 5.2.6 on 2025-10-16 05:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_entidad_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='foto_portada',
            field=models.ImageField(blank=True, default='entidades/default.webp', null=True, upload_to=accounts.models.entidad_cover_upload_to),
        ),
    ]
