# Generated by Django 5.2.6 on 2025-10-16 05:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_entidad_foto_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.anuncio_pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.anuncio_banner_upload_to),
        ),
    ]
