# Generated by Django 5.2.6 on 2025-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_anuncio_archivo_pdf_alter_anuncio_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
