# Generated by Django 5.2.6 on 2025-10-21 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_anuncio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 3, 15, 7, 648444, tzinfo=datetime.timezone.utc)),
        ),
    ]
