# Generated by Django 5.2.6 on 2025-11-02 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 18, 50, 39, 212250, tzinfo=datetime.timezone.utc)),
        ),
    ]
