# Generated by Django 5.2.6 on 2025-11-04 05:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accounts.anuncio'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='notificaciones/banners/'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 5, 30, 36, 944972, tzinfo=datetime.timezone.utc)),
        ),
    ]
