# Generated by Django 5.2.6 on 2025-11-04 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notificacion_anuncio_notificacion_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 6, 33, 52, 737716, tzinfo=datetime.timezone.utc)),
        ),
    ]
