# Generated by Django 5.2.6 on 2025-11-04 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_notificacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 8, 53, 32, 528516, tzinfo=datetime.timezone.utc)),
        ),
    ]
