# Generated by Django 5.2.6 on 2025-11-12 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 3, 46, 50, 562252, tzinfo=datetime.timezone.utc)),
        ),
    ]
