# Generated by Django 5.2.6 on 2025-11-12 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_entidad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 5, 0, 29, 813439, tzinfo=datetime.timezone.utc)),
        ),
    ]
