# Generated by Django 5.2.6 on 2025-11-12 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 5, 21, 45, 771136, tzinfo=datetime.timezone.utc)),
        ),
    ]
