# Generated by Django 5.2.6 on 2025-12-02 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 3, 20, 31, 42, 670157, tzinfo=datetime.timezone.utc)),
        ),
    ]
