# Generated by Django 5.2.6 on 2025-11-26 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 6, 9, 9, 321410, tzinfo=datetime.timezone.utc)),
        ),
    ]
